trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd payment-api
    npm run install:all
  displayName: 'Install application dependencies'

- script: |
    cd payment-api
    npm run build
  displayName: 'Build application'

- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'vishalkangude/payment-platform'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/payment-api/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)/payment-api'
    tags: |
      $(Build.BuildId)
      latest